### ISSUE TITLE
Needs help with updating Blue Coffee to main branch

### ISSUE THREAD

**Issue by Qwart376** [leftwm/leftwm-community-themes#15]
I've changed the border and margin size, but I can't edit the branch for some reason. Any help or explanation?

**Comment by AethanFoot** [comment]
To update you just need to push to the git repo the theme is on, nothing needs to be altered on the leftwm-community-themes repo. Hope this helps.
Thanks.

**Comment by Qwart376** [comment]
Thanks. I keep seeing an outdated branch here that I couldn't change, so I was a bit worried
