### ISSUE TITLE
Layout and resizing need improvement

### ISSUE THREAD

**Issue by Qwart376** [leftwm/leftwm-community-themes#16]
Sorry to say this, but the resizing is useless. Once you resize a window, it goes into floating mode while other windows adjust to the grid and hide under it. It should be also resized by arrow keys because TWM's are focused around keyboard use, and sudden need to switch to mouse/touchpad can be a pain in the ass (other TWMs are allowing to change this with keys)

The layouts itself are fine, but there should be also shortcuts for each of them. Having to constantly circle through them is annoying 

LeftWM is overall great, but current resizing makes me want to switch to something else. The default layouts itself are not that great for work, and the config file keeps bricking if you make a single error (leftwm returns to stock keybinds and stays there)

**Comment by lex148** [comment]
hey @Qwart376 

A lot of the layouts support the commands (IncreaseMainWidth, DecreaseMainWidth) I use these to resize my windows instead of trying to make them float. 

Here is what I have in my config. 

```
[[keybind]]
command = "IncreaseMainWidth"
value = "5"
modifier = ["modkey"]
key = "semicolon"
[[keybind]]
command = "DecreaseMainWidth"
value = "5"
modifier = ["modkey"]
key = "j"

```

I would also recommend running the command `leftwm-check` I run it every time I make a change to my config. that way it tells me when I do something wrong in the config. 

Hope this helps,

lex148

**Comment by Qwart376** [comment]
> hey @Qwart376
> 
> A lot of the layouts support the commands (IncreaseMainWidth, DecreaseMainWidth) I use these to resize my windows instead of trying to make them float.
> 
> Here is what I have in my config.
> 
> ```
> [[keybind]]
> command = "IncreaseMainWidth"
> value = "5"
> modifier = ["modkey"]
> key = "semicolon"
> [[keybind]]
> command = "DecreaseMainWidth"
> value = "5"
> modifier = ["modkey"]
> key = "j"
> ```
> 
> I would also recommend running the command `leftwm-check` I run it every time I make a change to my config. that way it tells me when I do something wrong in the config.
> 
> Hope this helps,
> 
> lex148

Thanks and sorry for closing this so late. It would be nice if there was also command to change height of the window
