### ISSUE TITLE
Double Bar in known.toml error

### ISSUE THREAD

**Issue by PeterDauwe** [leftwm/leftwm-community-themes#47]
In known.toml 
```
[[theme]]
name = "Double Bar"
repository = "https://github.com/leftwm/leftwm-community-themes/"
relative_directory = "doublebar/"
commit = "*"
version = "0.0.1"
leftwm_versions = "<0.3.0"
```

That repository line downloads all the themes!!!!!! inside a directory doublebar.

**Comment by VuiMuich** [comment]
This most certainly looks like a bug with processing the `relative_directory`, I am just not sure at which point this fails.

**note: edited in the code block for better readability in the original post. I hope you wont take this offensive.

**Comment by PeterDauwe** [comment]
None taken.
Well I know a solution.
```
[[theme]]
name = "doublebar"
repository = "https://github.com/PeterDauwe/doublebar/"
relative_directory = "doublebar/"
commit = "*"
version = "0.0.1"
leftwm_versions = "<0.3.0"
```

**Comment by VuiMuich** [comment]
I just had a look at the code, the `relatvie_ditectory` is only ever used when applying the theme.
So of course this doesn't get parsed for cloning the theme. We probably should see to document this better.

I'll directly push a fix in a minute.

**Comment by VuiMuich** [comment]
@PeterDauwe I took this opportunity to make `Double Bar` a submodule, just as the other themes. For updates you push to  your own repo only.
