### ISSUE TITLE
Deleted upstream

### ISSUE THREAD

**Issue by 0323pin** [leftwm/leftwm-community-themes#56]
Hi,

The following GitHub account has been deleted and the theme is no longer available.
![Capture](https://user-images.githubusercontent.com/90570748/161003541-1fd86de3-fc65-46de-ad28-d07dd8a08427.PNG)

**Comment by VuiMuich** [comment]
Thanks for the heads up. Would we want to remove or should we restore from some local copy?

**Comment by 0323pin** [comment]
@VuiMuich That's really up to you but, I'd say **_keep_** if the theme has something that can not be found on any of the other themes and **_remove_** if it doesn't bring anything to the table.

**Comment by 0323pin** [comment]
And another one deleted, just a few days after being uploaded, https://github.com/minda1975/minimal_solarized/tree/8b922faf4861af31aec8c7fc44bb3fc55f88a9bd

Maybe it's not clear that original repositories shouldn't be deleted after merge, since themes should be hosted at origin.
